# Generated by Django 5.2 on 2025-04-18 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure_months', models.IntegerField()),
                ('interest_rate', models.FloatField(default=7.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maturity_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
