# Generated by Django 5.2 on 2025-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_account_balance_alter_account_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='tenure_months',
            field=models.IntegerField(default=12),
        ),
    ]
