# Generated by Django 5.2 on 2025-04-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_fixeddeposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
